Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,26 @@ jobs:
       - name: Install bpmnlint
         run: npm install -g bpmnlint
         
-      - name: Run custom validation script
+      - name: Copy custom rules
         run: |
-          node -e "const validationScript = require('./validate-bpmn.js'); validationScript.copyCustomRules('${{ inputs.custom-rules-folder }}'); validationScript.listAvailableRules(); validationScript.createBpmnlintrcFile('${{ inputs.bpmnlintrc-path }}'); validationScript.runBpmnValidation('${{ inputs.bpmn-files-path }}');"
+          cp -r ${{ inputs.custom-rules-folder }}/* /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules/
+        working-directory: ${{ github.workspace }}
+        
+      - name: List all available rules
+        run: ls -al /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules
+        
+      - name: Read and create .bpmnlintrc configuration file
+        run: |
+          cat "${{ inputs.bpmnlintrc-path }}" > .bpmnlintrc.txt
+          mv .bpmnlintrc.txt .bpmnlintrc
+
+      - name: Run BPMN validation and output result
+        run: |
+          for file in ${{ inputs.bpmn-files-path }}/*.bpmn; do
+            if [ -z "$(bpmnlint "$file")" ]; then
+              echo -e "\033[32mNo errors found in $file\033[0m"
+            else
+              echo -e "\033[31mErrors found in $file:\033[0m"
+              bpmnlint "$file" || true
+            fi
+          done  
