Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,20 +30,25 @@ jobs:
         run: npm install -g bpmnlint
         
       - name: Copy custom rules
-        run: node run-bpmn-validation.js copy-rules
-        env:
-          CUSTOM_RULES_FOLDER: ${{ inputs.custom-rules-folder }}
+        run: |
+          cp -r ${{ inputs.custom-rules-folder }}/* /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules/
         working-directory: ${{ github.workspace }}
         
       - name: List all available rules
-        run: node run-bpmn-validation.js list-rules
+        run: ls -al /opt/hostedtoolcache/node/18.17.0/x64/lib/node_modules/bpmnlint/rules
         
       - name: Read and create .bpmnlintrc configuration file
-        run: node run-bpmn-validation.js create-lintrc
-        env:
-          BPMNLINTRC_PATH: ${{ inputs.bpmnlintrc-path }}
-        
+        run: |
+          cat "${{ inputs.bpmnlintrc-path }}" > .bpmnlintrc.txt
+          mv .bpmnlintrc.txt .bpmnlintrc
+
       - name: Run BPMN validation and output result
-        run: node run-bpmn-validation.js run-validation
-        env:
-          BPMN_FILES_PATH: ${{ inputs.bpmn-files-path }}
+        run: |
+          for file in ${{ inputs.bpmn-files-path }}/*.bpmn; do
+            if [ -z "$(bpmnlint "$file")" ]; then
+              echo -e "\033[32mNo errors found in $file\033[0m"
+            else
+              echo -e "\033[31mErrors found in $file:\033[0m"
+              bpmnlint "$file" || true
+            fi
+          done  
